// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiH01d_bWXqGuu4lQafFDuDmrfbnQjoA4',
    appId: '1:632085793199:web:64563abd2d0d8faad2c75a',
    messagingSenderId: '632085793199',
    projectId: 'bcv1-f450b',
    authDomain: 'bcv1-f450b.firebaseapp.com',
    databaseURL: 'https://bcv1-f450b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bcv1-f450b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrFK8HL0bBK7QaVm5dsQJ9Gk9Nm5-LmlU',
    appId: '1:632085793199:android:e4ef41aaa70c963ad2c75a',
    messagingSenderId: '632085793199',
    projectId: 'bcv1-f450b',
    databaseURL: 'https://bcv1-f450b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bcv1-f450b.appspot.com',
  );

}